# -*- coding: utf-8 -*-
"""Hyperparameters in MLP.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CF75T2bTh0DyfS4VGTfEzmo5HeHX5_i8
"""

import torch
import torch.nn as nn
from torchvision import datasets, transforms
from torch.utils.data import DataLoader, random_split

# ───────────────────────────────
# 1. ДАННЫЕ
# ───────────────────────────────

transform = transforms.ToTensor()

full_train = datasets.CIFAR10('./data', train=True,  download=True, transform=transform)
test_data  = datasets.CIFAR10('./data', train=False, download=True, transform=transform)

# Делим train на 90% обучение и 10% валидация
val_size   = int(0.1 * len(full_train))   # 5000 картинок
train_size = len(full_train) - val_size   # 45000 картинок

train_data, val_data = random_split(full_train, [train_size, val_size])

train_loader = DataLoader(train_data, batch_size=64, shuffle=True)
val_loader   = DataLoader(val_data,   batch_size=64, shuffle=False)

# ───────────────────────────────
# 2. АРХИТЕКТУРА
# ───────────────────────────────

class MLP(nn.Module):
    def __init__(self, activation):
        super().__init__()
        self.net = nn.Sequential(
            nn.Flatten(),              # 3×32×32 → вектор 3072
            nn.Linear(3072, 512),      # первый слой
            activation,                # ReLU или GELU
            nn.Linear(512, 10)         # второй слой → 10 классов
        )

    def forward(self, x):
        return self.net(x)

# ───────────────────────────────
# 3. ФУНКЦИИ ОБУЧЕНИЯ И ОЦЕНКИ
# ───────────────────────────────

def train_epoch(model, loader, optimizer, loss_fn):
    model.train()
    total_loss = 0
    for images, labels in loader:
        optimizer.zero_grad()
        outputs = model(images)
        loss = loss_fn(outputs, labels)
        loss.backward()
        optimizer.step()
        total_loss += loss.item()
    return total_loss / len(loader)   # средний loss за эпоху

def val_epoch(model, loader, loss_fn):
    model.eval()                      # выключаем dropout и т.п. (у нас их нет, но хорошая привычка)
    total_loss = 0
    with torch.no_grad():             # градиенты не нужны — не тратим память
        for images, labels in loader:
            outputs = model(images)
            loss = loss_fn(outputs, labels)
            total_loss += loss.item()
    return total_loss / len(loader)

# ───────────────────────────────
# 4. ПЕРЕБОР ГИПЕРПАРАМЕТРОВ
# ───────────────────────────────

configs = [
    {'activation': nn.ReLU(),  'lr': 0.1,   'name': 'ReLU  | lr=0.1  '},
    {'activation': nn.ReLU(),  'lr': 0.01,  'name': 'ReLU  | lr=0.01 '},
    {'activation': nn.ReLU(),  'lr': 0.001, 'name': 'ReLU  | lr=0.001'},
    {'activation': nn.GELU(),  'lr': 0.1,   'name': 'GELU  | lr=0.1  '},
    {'activation': nn.GELU(),  'lr': 0.01,  'name': 'GELU  | lr=0.01 '},
    {'activation': nn.GELU(),  'lr': 0.001, 'name': 'GELU  | lr=0.001'},
]

loss_fn = nn.CrossEntropyLoss()
EPOCHS  = 10

results = []

for cfg in configs:
    print(f"\n{'='*45}")
    print(f"  Запуск: {cfg['name']}")
    print(f"{'='*45}")

    model     = MLP(cfg['activation'])
    optimizer = torch.optim.SGD(model.parameters(), lr=cfg['lr'])

    best_val_loss = float('inf')

    for epoch in range(EPOCHS):
        train_loss = train_epoch(model, train_loader, optimizer, loss_fn)
        val_loss   = val_epoch(model, val_loader, loss_fn)

        if val_loss < best_val_loss:
            best_val_loss = val_loss

        print(f"  Эпоха {epoch+1:2d} | train_loss: {train_loss:.4f} | val_loss: {val_loss:.4f}")

    results.append({
        'name':          cfg['name'],
        'best_val_loss': best_val_loss
    })

# ───────────────────────────────
# 5. ЛУЧШАЯ КОНФИГУРАЦИЯ
# ───────────────────────────────

print(f"\n{'='*45}")
print("  ИТОГИ")
print(f"{'='*45}")

results.sort(key=lambda x: x['best_val_loss'])

for r in results:
    print(f"  {r['name']} | best val_loss: {r['best_val_loss']:.4f}")

print(f"\n  ✅ Лучшая конфигурация: {results[0]['name']}")
print(f"     val_loss = {results[0]['best_val_loss']:.4f}")